version: '2'

services:
    db:
        container_name: mysql
        image: mysql:latest
        ports:
            - 3306:3306
        volumes:
            - .data/db:/var/lib/mysql
        environment:
            MYSQL_ROOT_PASSWORD: soSecretICantEven
            MYSQL_DATABASE: dev
            MYSQL_USER: dev
            MYSQL_PASSWORD: dev
        command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_general_ci

    php:
        container_name: php
        build: php7-fpm
        ports:
            - 9000:9000
        links:
            - db:mysqldb
        volumes:
            - ../promoters-backend:/var/www/symfony
            - ./logs/symfony:/var/www/symfony/app/logs

    nginx:
        container_name: nginx
        build: nginx
        ports:
            - 80:80
        links:
            - php
        volumes_from:
            - php
        volumes:
            - ./logs/nginx:/var/log/nginx
